# Generated by Django 3.0.5 on 2022-02-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('fish_id', models.AutoField(primary_key=True, serialize=False)),
                ('fish_name', models.CharField(default='', max_length=50)),
                ('fish_species', models.CharField(default='', max_length=50)),
                ('weight', models.FloatField(default=2.0)),
                ('length', models.FloatField(default=0.5)),
                ('lattitude', models.FloatField(default=28.7)),
                ('longitude', models.FloatField(default=77.1)),
                ('timestamp', models.DateTimeField(default='2022/02/22 01:32:49')),
            ],
        ),
    ]
