# Generated by Django 3.0.5 on 2022-02-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bezen_rest', '0003_auto_20220222_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='timestamp',
            field=models.DateTimeField(default='2022-02-22-10:56:50'),
        ),
    ]
