# Generated by Django 3.0.5 on 2022-02-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bezen_rest', '0005_auto_20220222_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/<django.db.models.fields.AutoField>/'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='timestamp',
            field=models.DateTimeField(default='2022-02-22 12:56:39'),
        ),
    ]
