# Generated by Django 3.0.5 on 2022-02-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bezen_rest', '0006_auto_20220222_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='img',
        ),
        migrations.AddField(
            model_name='fish',
            name='<django.db.models.fields.AutoField>.png',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='fish',
            name='timestamp',
            field=models.DateTimeField(default='2022-02-22 17:30:14'),
        ),
    ]
