# Generated by Django 3.0.5 on 2022-02-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bezen_rest', '0007_auto_20220222_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='<django.db.models.fields.AutoField>.png',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='fish',
            name='timestamp',
            field=models.DateTimeField(default='2022-02-22 17:36:39'),
        ),
    ]
