# Generated by Django 3.0.5 on 2022-02-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bezen_rest', '0009_auto_20220223_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedfish',
            name='fish_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fish',
            name='timestamp',
            field=models.DateTimeField(default='2022-02-23 11:43:02'),
        ),
    ]
