# Generated by Django 3.0.5 on 2022-02-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bezen_rest', '0010_auto_20220223_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedfish',
            old_name='id',
            new_name='_id',
        ),
        migrations.AlterField(
            model_name='fish',
            name='timestamp',
            field=models.DateTimeField(default='2022-02-23 12:19:00'),
        ),
        migrations.AlterField(
            model_name='processedfish',
            name='img_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
